### ISSUE TITLE
Cannot find "Manage NuGet Packages"

### ISSUE THREAD

**Issue by TKan010714** [ptrpaws/Among-Us-Trasher#4]
Hi, I read the "How To Use" instructions but I can't seem to find the "Manage NuGet Packages".

I did the first step and clicked "Projects".
Not sure what to next because I can't find "Manage NuGet Packages".

Here's a screenshot
https://i.imgur.com/CdYuFw3.png

**Comment by ptrpaws** [comment]
Hello @TKan010714 , 

you can access the NuGet package manager from within Visual Studio, which is available [here](https://visualstudio.microsoft.com/vs/community/)
I'll add a note in the "How to use" section of the readme in order to clarify that this is a Visual Studio project.
 ##

Thank you for your feedback!
